### PR TITLE
Added shorter wasCalled(int) method

### PR DESCRIPTION
**Pull request by Thieveryshoe**
In my experience, verifying that a method was called one time will be the most often used combination of arguments, therefore added the convenience method.

### CODE REVIEW

**Comment by surajp** [comment]
@Thieveryshoe this makes sense. I am wondering if it makes sense to also add a `wasCalled` method with no arguments that equates to `wasCalled(1,UniversalMocker.TIMES.OR_MORE)` . Also, this/these will need to be added to the README. @elements inviting comments here from you as well

**Comment by Thieveryshoe** [comment]
I can update the readme once we finalize here.

Let's pretend for a moment that we have access to `wasCalledOnce()` and `wasCalled()`.  What kind of scenarios can we come up with to justify having my suggestion, both suggestions, or neither.

`wasCalledOnce()` is really just a convenience method from the point of autocomplete/intellisense.  The way I test/write code, this is by far the most common verification that I use.  Sure it does save a few characters, but at the end of the day, I just want that sweet autocomplete.

If both options are available, I can see a scenario arising where someone intends to use `wasCalledOnce()` but mistypes `wasCalled()`.  I suspect that type of error would be hard to detect if one were just reading the tests.  Would it be wise to post-fix with something like, `wasCalled() => wasCalledAny()`?  

@elements  Get in here, you use this lib more than I do. 😃

**Comment by elements** [comment]
I agree with @Thieveryshoe  that I'm checking for once alot but I'm also checking if something is called 2 or 3 often too.

I think think would be cleaner `wasCalled({integer})` and have to run `UniversalMocker.Times.EXACTLY`. It feels more fluid in most workflows people are matching that its been called exact number of times. I don't think I never checked anything but `EXACTLY` because my tests are very prescriptive.

This could also remove `wasNeverCalled()` by replacing it to do `wasCalled(0)`

**Comment by Thieveryshoe** [comment]
Yeah I like `wasCalled(int)` as well, that's a solid happy medium.  I'm all for leaving the `wasNeverCalled()` function as it is very explicit.  Easy to ctrl+f for "never" and also when you're reading the asserts, it's explicit.

**Comment by surajp** [comment]
Agree on both counts @Thieveryshoe . Also, I prefer not to change the API unless absolutely necessary, so we will leave `wasNeverCalled` as is. Care to update your changes to include `wasCalled({integer})` instead of `wasCalledOnce` and update the Readme as well?

**Comment by surajp** [comment]
Thanks for the suggestion @elements . Very helpful!

**Comment by Thieveryshoe** [comment]
> Agree on both counts @Thieveryshoe . Also, I prefer not to change the API unless absolutely necessary, so we will leave `wasNeverCalled` as is. Care to update your changes to include `wasCalled({integer})` instead of `wasCalledOnce` and update the Readme as well?

Yup, I'll knock it out over the next week sometime.  Thanks fellas.

**Comment by Thieveryshoe** [comment]
Alright, have a look @surajp and let me know if there's anything else we need.  I like these changes a lot.

**Pull request merged**
